title: 'Ministry of Law - Licensing & Regulation of Insolvency Practitioners'
description: Description
url: 'https://lripd.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    general-information:
        output: true
    information-for-insolvency-practitioners:
        output: true
    information-for-public:
        output: true
    about:
        output: true
favicon: /images/favicon-mlaw.ico
google-analytics: null
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
