title: 'Ministry of Law - Licensing & Regulation of Insolvency Practitioners'
description: Description
url: 'https://lripd.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
favicon: /images/favicon-mlaw.ico
google-analytics: null
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://mlaw-lripd-staging.netlify.app
prod: https://mlaw-lripd-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
